-- Generated by http://csv2sql.com online CSV to SQL converter

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Ainslie School','Donaldson Street','Braddon','Government','(-35.273729, 149.139632)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Alfred Deakin High School','Denison Street','Deakin','Government','(-35.323849, 149.094282)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Amaroo School','Katherine Avenue','Amaroo','Government','(-35.16392, 149.125588)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Aranda Primary School','Banambila Crescent','Aranda','Government','(-35.255999, 149.079914)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Arawang Primary School','Nemarang Crescent','Waramanga','Government','(-35.355017, 149.059719)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Belconnen High School','Murranji Street','Hawker','Government','(-35.246957, 149.039298)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Birrigai Outdoor School','Tidbinbilla Road','THARWA','Government','(-35.45, 148.96)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Black Mountain School','Dryandra Street','O\'Connor','Government','(-35.265224, 149.112366)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Blue Gum Community School','114 Maitland Street','HACKETT','Non-Government','(-35.246571, 149.15938)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Bonython Primary School','Hurtle Avenue','Bonython','Government','(-35.431846, 149.082604)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Brindabella Christian College','136 Brigalow Street','LYNEHAM','Non-Government','(-35.248056, 149.12805)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Burgmann Anglican School','Cnr The Valley Avenue and Gungahlin Drive','GUNGAHLIN','Non-Government','(-35.188529, 149.123672)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Burgmann Anglican School - Forde Campus','Francis Forde Boulevard','FORDE','Non-Government','(-35.169949, 149.14722)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Calwell High School','Casey Crescent','Calwell','Government','(-35.441052, 149.117635)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Calwell Primary School','Downard Street','Calwell','Government','(-35.438412, 149.109254)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Campbell High School','Treloar Crescent','Campbell','Government','(-35.278101, 149.147123)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Campbell Primary School','Chauvel Street','Campbell','Government','(-35.290271, 149.156099)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Canberra Christian School','Ainsworth Street','MAWSON','Non-Government','(-35.356475, 149.097963)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Canberra College, The ','Launceston Street','Phillip','Government','(-35.34036, 149.088321)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Canberra College, The - Weston','Fremantle Drive','Stirling','Government','(-35.3404, 149.0883)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Canberra Girls\' Grammar School','Melbourne Avenue','DEAKIN','Non-Government','(-35.31699, 149.115115)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Canberra Girls\' Grammar Junior School','Grey Street','DEAKIN','Non-Government','(-35.312126, 149.110759)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Canberra Grammar School','Monaro Crescent','RED HILL','Non-Government','(-35.330919, 149.124674)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Canberra Grammar School (Northside Infants)','Blamey Crescent','CAMPBELL','Non-Government','(-35.285316, 149.147091)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Canberra Grammar Junior School','Alexander Street','RED HILL','Non-Government','(-35.332344, 149.124691)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Canberra High School','Bindubi Street','Macquarie','Government','(-35.251302, 149.074517)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Canberra Montessori School','35 Mulley Street','HOLDER','Non-Government','(-35.332247, 149.051068)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Canberra Montessori School','28 Astrolabe Street','RED HILL','Non-Government','(-35.339388, 149.133153)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Caroline Chisholm School','Hambridge Crescent','Chisholm','Government','(-35.418155, 149.122047)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Chapman Primary School','Perry Drive','Chapman','Government','(-35.356878, 149.043079)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Charles Conder Primary School','Tom Roberts Avenue','Conder','Government','(-35.464883, 149.098449)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Charnwood-Dunlop School','Bettington Circuit','Charnwood','Government','(-35.198682, 149.036203)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Covenant College','Woodcock Drv','GORDON','Non-Government','(-35.439222, 149.090709)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Cranleigh School','Starke Street','Holt','Government','(-35.224913, 149.02911)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Curtin Primary School','Theodore Street','Curtin','Government','(-35.331662, 149.079926)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Daramalan College','Cowper Street','DICKSON','Non-Government','(-35.253518, 149.138695)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Dickson College','Phillip Avenue','Dickson','Government','(-35.248452, 149.154143)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Duffy Primary School','Burrinjuck Crescent','Duffy','Government','(-35.334219, 149.033656)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Emmaus Christian School','Davenport Street','DICKSON','Non-Government','(-35.253355, 149.142818)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Erindale College','McBryde Crescent','Wanniassa','Government','(-35.403473, 149.095654)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Evatt Primary School','Heydon Crescent','Evatt','Government','(-35.20707, 149.075906)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Fadden Primary School','Hanlon Crescent','Fadden','Government','(-35.404286, 149.118175)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Farrer Primary School','Lambrigg Street','Farrer','Government','(-35.378739, 149.107114)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Florey Primary School','Ratcliffe Crescent','Florey','Government','(-35.226519, 149.052092)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Forrest Primary School','National Circuit','Forrest','Government','(-35.315084, 149.126171)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Fraser Primary School','Tillyard Drive','Fraser','Government','(-35.191795, 149.043375)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Galilee School, The ','Kambah Pool Road','KAMBAH','Non-Government','(-35.386837, 149.03132)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Garran Primary School','Gilmore Crescent','Garran','Government','(-35.344681, 149.103287)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Gilmore Primary School','Heagney Crescent','Gilmore','Government','(-35.419488, 149.135582)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Giralang Primary School','Canopus Crescent','Giralang','Government','(-35.213717, 149.094449)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Gold Creek School','Kelleway Avenue','Nicholls','Government','(-35.181275, 149.100262)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Good Shepherd Primary School','Burdekin Avenue','AMAROO','Non-Government','(-35.166843, 149.123922)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Gordon Primary School','Knoke Avenue','Gordon','Government','(-35.455517, 149.086978)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Gowrie Primary School','Jeffries Street','Gowrie','Government','(-35.413608, 149.110565)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Gungahlin College','Gribble st','Gungahlin','Government','(-35.184283, 149.130617)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Harrison School','Nullabor Avenue','Harrison','Government','(-35.197531, 149.151642)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Hawker College','Murranji Street','Hawker','Government','(-35.244317, 149.031897)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Hawker Primary School','Erldunda Circuit','Hawker','Government','(-35.250284, 149.034593)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Holy Family Parish Primary School','Castleton Crescent','GOWRIE','Non-Government','(-35.410301, 149.116552)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Holy Spirit Primary School','Kelleway Avenue','NICHOLLS','Non-Government','(-35.180246, 149.101809)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Holy Trinity Primary School','Theodore Street','CURTIN','Non-Government','(-35.327679, 149.081951)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Hughes Primary School','Kent Street','Hughes','Government','(-35.332248, 149.093456)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Isabella Plains Early Childhood School','Ellerston Avenue','Isabella Plains','Government','(-35.428716, 149.089497)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Islamic School of Canberra','33 Heysen Street','Weston','Non-Government','(-35.329596, 149.060593)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Jervis Bay Primary School','Dykes Avenue','Jervis Bay','Government','(-35.130785, 150.704945)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Kaleen High School','Baldwin Drive','Kaleen','Government','(-35.225083, 149.1012)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Kaleen Primary School','Ashburton Circuit','Kaleen','Government','(-35.224835, 149.11404)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Kingsford Smith School','Starke Street','Holt','Government','(-35.227715, 149.019506)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Lake Ginninderra College','Emu Bank','Belconnen','Government','(-35.239149, 149.074161)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Lake Tuggeranong College','Cowlishaw Street','Tuggeranong','Government','(-35.413803, 149.068195)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Lanyon High School','Heidelberg Street','Conder','Government','(-35.460389, 149.09507)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Latham Primary School','O\'Loghlen Street','Latham','Government','(-35.220157, 149.034298)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Lyneham High School','Goodwin Street','Lyneham','Government','(-35.252379, 149.130653)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Lyneham Primary School','Hall Street','Lyneham','Government','(-35.25148, 149.124974)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Lyons Early Childhood School','Tarraleah Crescent','Lyons','Government','(-35.341633, 149.076243)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Macgregor Primary School','Hirschfeld Crescent','Macgregor','Government','(-35.213112, 149.012349)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Macquarie Primary School','Bennelong Crescent','Macquarie','Government','(-35.250069, 149.059393)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Majura Primary School','Knox Street','Watson','Government','(-35.238509, 149.15501)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Malkara School','Wisdom Street','Garran','Government','(-35.337447, 149.09402)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Maribyrnong Primary School','Alberga Street','Kaleen','Government','(-35.235115, 149.102261)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Marist College Canberra','Marr Street','PEARCE','Non-Government','(-35.357959, 149.088697)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Mawson Primary School','Ainsworth Street','Mawson','Government','(-35.358505, 149.097655)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Melba Copland Secondary School Copland Campus','Copland Drive','Melba','Government','(-35.21254, 149.059794)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Melba Copland Secondary School Melba Campus','Conley Drive','Melba','Government','(-35.21411, 149.049203)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Melrose High School','Marr Street','Pearce','Government','(-35.363475, 149.089434)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Merici College','Wise Street','BRADDON','Non-Government','(-35.266525, 149.137037)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Miles Franklin Primary School','Alderman Street','Evatt','Government','(-35.213295, 149.066961)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Monash Primary School','Corlette Street','Monash','Government','(-35.414879, 149.089411)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Mother Teresa Primary School','Corner of Mapleton Ave and Wimmera St','Harrison','Non-Government','(-35.195134, 149.15333)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Mount Rogers Primary School','Alfred Hill Drive','Melba','Government','(-35.208737, 149.055621)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Namadgi School','O\'Halloran Cct','Kambah','Government','(-35.392796, 149.067127)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Narrabundah College','Jerrabomberra Ave','Narrabundah','Government','(-35.335969, 149.147097)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Narrabundah Early Childhood School','Kootara Crescent','Narrabundah','Government','(-35.329016, 149.150698)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Ngunnawal Primary School','Unaipon Avenue','Ngunnawal','Government','(-35.169196, 149.111784)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('North Ainslie Primary School','Majura Avenue','Ainslie','Government','(-35.255113, 149.146358)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('O\'Connor Cooperative School','Macpherson Street','O\'Connor','Government','(-35.264552, 149.122499)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Orana School','Unwin Place','WESTON','Non-Government','(-35.327858, 149.058949)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Palmerston District Primary School','Kosciusko Avenue','Palmerston','Government','(-35.1975, 149.120303)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Radford College','College Street','BRUCE','Non-Government','(-35.243503, 149.089323)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Red Hill Primary School','Astrolabe Street','Red Hill','Government','(-35.339741, 149.132893)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Richardson Primary School','May Gibbs Close','Richardson','Government','(-35.428859, 149.113943)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Rosary Primary School','Fleming Street','WATSON','Non-Government','(-35.24641, 149.154682)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Sacred Heart Primary School','29 Murphy Street','PEARCE','Non-Government','(-35.366936, 149.084391)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Southern Cross Early Childhood School','Wirraway Crescent','Scullin','Government','(-35.232767, 149.038363)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('St Anthony\'s Parish School','Wheeler Crescent','WANNIASSA','Non-Government','(-35.394049, 149.080086)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('St Bede\'s Primary School','Nuyts Street','RED HILL','Non-Government','(-35.338847, 149.128788)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('St Benedict\'s Primary School','Tallara Parkway','NARRABUNDAH','Non-Government','(-35.33483, 149.148034)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('St Clare of Assisi Primary School','Cnr Boxhill Avenue and Heidelberg Street','CONDER','Non-Government','(-35.45791, 149.096766)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('St Clare\'s College','McMillan Crescent','GRIFFITH','Non-Government','(-35.323929, 149.14765)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('St Edmund\'s College','Canberra Avenue','GRIFFITH','Non-Government','(-35.32282, 149.144242)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('St Francis of Assisi Primary School','Casey Crescent','CALWELL','Non-Government','(-35.440799, 149.119593)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('St Francis Xavier College','Barnard Circuit','FLOREY','Non-Government','(-35.223979, 149.040615)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('St John the Apostle Primary School','Pawsey Circuit','FLOREY','Non-Government','(-35.225664, 149.041696)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('St John Vianney\'s Primary School','Namatjira Drv','WARAMANGA','Non-Government','(-35.351057, 149.055559)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('St Joseph\'s Primary School','Macarthur Avenue','O\'CONNOR','Non-Government','(-35.259648, 149.126375)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('St Jude\'s Primary School','Mulley Street','HOLDER','Non-Government','(-35.333941, 149.049819)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('St Mary Mackillop College','Ellerston Avenue','ISABELLA PLAINS','Non-Government','(-35.424911, 149.092808)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('St Mary Mackillop College','Mackinnon Street','WANNIASSA','Non-Government','(-35.405251, 149.090983)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('St Matthew\'s Primary School','Stutchbury Street','PAGE','Non-Government','(-35.240755, 149.041555)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('St Michael\'s Primary School','Tyrell Circuit','KALEEN','Non-Government','(-35.223474, 149.109707)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('St Monica\'s Primary School','Moynihan Street','EVATT','Non-Government','(-35.213525, 149.061289)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('St Thomas Aquinas Primary School','Lhotsky Street','CHARNWOOD','Non-Government','(-35.205121, 149.029638)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('St Thomas More\'s Primary School','24 White Crescent','CAMPBELL','Non-Government','(-35.286717, 149.156836)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('St Thomas the Apostle Primary School','Boddington Crescent','KAMBAH','Non-Government','(-35.382449, 149.051977)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('St Vincent\'s Primary School','Bindel Street','ARANDA','Non-Government','(-35.254993, 149.076661)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Stromlo High School','Badimara Street','Waramanga','Government','(-35.355429, 149.05436)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Sts Peter and Paul\'s Primary School','Wisdom Street','GARRAN','Non-Government','(-35.339376, 149.092732)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Taylor Primary School','Marconi Crescent','Kambah','Government','(-35.378318, 149.064261)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Telopea Park School','New South Wales Crescent','Barton','Government','(-35.313804, 149.134385)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Theodore Primary School','Lawrence-Wackett Crescent','Theodore','Government','(-35.447667, 149.12396)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Torrens Primary School','Ritchie Street','Torrens','Government','(-35.370046, 149.090949)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Trinity Christian School','34 McBryde Crs','WANNIASSA','Non-Government','(-35.408265, 149.086051)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Turner School','Condamine Street','Turner','Government','(-35.264995, 149.126081)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Wanniassa Hills Primary School','Langdon Avenue','Wanniassa','Government','(-35.393069, 149.095898)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Wanniassa School','Sternberg Crescent','Wanniassa','Government','(-35.398201, 149.086012)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Wanniassa School','Wheeler Crescent','Wanniassa','Government','(-35.394992, 149.086363)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Weetangera Primary School','Southwell Street','Weetangera','Government','(-35.251826, 149.047137)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Woden School, The ','Denison Street','Deakin','Government','(-35.326599, 149.092398)');

INSERT INTO schools (`School Name`,`Street Address`,`Suburb`,`Sector`,`Location 1`) VALUES ('Yarralumla Primary School','Loftus Street','Yarralumla','Government','(-35.306948, 149.103234)');

